//update..
//install postgres
//run setup script
//install postgresql-contrib
// sudo -u postgres psql postgres
//cd /usr/share/postgresql/9.6/contrib/
//psql -U postgres -d lehelchatbot -f pgcrypto.sql
//restart pg service
//install phoenix
//install git
//clone project
//run mix commands
//npm install
//install ssl cert
//launch web service



//run tests...
//configure ports