//update..
//install postgres
//run setup script
//restart pg service
//install phoenix
//install git
//clone project
//run mix commands
//npm install
//install ssl cert
//launch web service



//run tests...
//configure ports