version: "3"

services:

  webapp:
    build:
      context: .
      dockerfile: phoenix.dockerfile
    ports:
       - "4000:4000"
       - "4443:4443"
    working_dir: /code
    networks: 
       - lehel-network
    volumes:
     - .:/code/lehelchatbot
     - .:/code/lehelchatbot/node_modules
    #command: ['./wait-for-it.sh', 'postgres:5439', '--', './post-webapp-up.sh']
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    ports:
       - "5439:5439"
    restart: always
    environment:
       - DEBUG=false
       - DB_USER=postgres
       - DB_PASS=postgres
       - DB_NAME=lehelchatbox
       - DB_TEMPLATE=
       - DB_EXTENSION=pgcrypto
    networks:
       - lehel-network

networks:
  lehel-network:
    driver: bridge


